# Generated by Django 4.2.8 on 2023-12-30 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sonsors',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('sensor_unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sensor_name', models.CharField(default='', max_length=9000)),
                ('serial_number', models.CharField(max_length=7, unique=True)),
                ('sensor_type', models.CharField(choices=[('GAS_DEVICE', 'GAS_DEVICE'), ('FUEL_DEVICE', 'FUEL_DEVICE')], default='', max_length=9000, null=True)),
                ('sensor_is_active', models.BooleanField(default=True)),
                ('sensor_registered_date', models.DateTimeField(auto_now_add=True)),
                ('sensor_registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_registered_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sensors',
                'db_table': 'fuel_sensors_tbl',
                'db_table_comment': 'This Table Used to Store IOT Sensors for reading Fuel Levels',
                'ordering': ['-primary_key'],
            },
        ),
    ]
