# Generated by Django 4.2.8 on 2024-01-14 08:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('management_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanduyServices',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('service_unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('service_name', models.CharField(default='Ibada ya Jumapili', max_length=9000)),
                ('service_registered_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'SErvices',
                'db_table': 'sunday_service_name_tbl',
                'db_table_comment': 'Cronjob based table for registrering sunday services',
                'ordering': ['-primary_key'],
            },
        ),
        migrations.DeleteModel(
            name='Sonsors',
        ),
    ]
