# Generated by Django 4.2.8 on 2024-01-14 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_panel', '0002_sanduyservices_delete_sonsors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SanduyServices',
        ),
    ]
