# Generated by Django 4.2.8 on 2024-01-14 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_panel', '0004_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sundayservices',
            options={'ordering': ['-primary_key'], 'verbose_name_plural': 'Services'},
        ),
    ]
