# Generated by Django 4.2.8 on 2024-01-14 10:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('members_management', '0001_initial'),
        ('management_panel', '0005_alter_sundayservices_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sundayservices',
            options={'ordering': ['-primary_key'], 'verbose_name_plural': '01. Services'},
        ),
        migrations.CreateModel(
            name='ChurchSerives',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('serive_unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('serive_name', models.CharField(blank=True, max_length=90, null=True)),
                ('serive_members', models.ManyToManyField(blank=True, related_name='serive_members', to='members_management.churchmembers')),
            ],
            options={
                'verbose_name_plural': '02. CHURCH SERIVCES',
                'db_table': 'church_services',
                'ordering': ['-primary_key'],
            },
        ),
    ]
