# Generated by Django 4.2.8 on 2024-01-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_panel', '0006_alter_sundayservices_options_churchserives'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='churchserives',
            options={'ordering': ['-primary_key'], 'verbose_name_plural': 'CHURCH SERIVCES'},
        ),
        migrations.AlterModelOptions(
            name='sundayservices',
            options={'ordering': ['-primary_key'], 'verbose_name_plural': 'SUNDAY SERIVCES'},
        ),
    ]
