# Generated by Django 4.2.8 on 2024-01-14 20:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('management_panel', '0007_alter_churchserives_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSTemplates',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('template_unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('template_name', models.CharField(default='', max_length=9000)),
                ('template_descriptions', models.CharField(default='', max_length=9000)),
                ('template_is_active', models.BooleanField(default=True)),
                ('template_registered_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'SMS TEMAPLTE',
                'db_table': 'sms_template_name_tbl',
                'db_table_comment': 'SMS Template Table',
                'ordering': ['-primary_key'],
            },
        ),
    ]
