# Generated by Django 4.2.8 on 2024-01-14 20:53

from django.db import migrations, models
import utils.Enums


class Migration(migrations.Migration):

    dependencies = [
        ('management_panel', '0008_smstemplates'),
    ]

    operations = [
        migrations.AddField(
            model_name='smstemplates',
            name='template_type',
            field=models.CharField(blank=True, choices=[('VISITORS', 'VISITORS'), ('PRAYERS', 'PRAYERS'), ('TENTHS', 'TENTHS'), ('GREETINGS', 'GREETINGS'), ('OTHER', 'OTHER')], default=utils.Enums.SMSTemplateInum['VISITORS'], max_length=9000, null=True),
        ),
    ]
