# Generated by Django 4.2.8 on 2024-01-16 17:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('members_management', '0005_alter_churchmembers_member_maritual_status'),
        ('management_panel', '0009_smstemplates_template_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smstemplates',
            name='template_descriptions',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='ChurchZones',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('zone_unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('zone_name', models.CharField(blank=True, max_length=90, null=True)),
                ('zone_members', models.ManyToManyField(blank=True, related_name='zone_members', to='members_management.churchmembers')),
            ],
            options={
                'verbose_name_plural': 'CHURCH ZONES',
                'db_table': 'church_zones',
                'ordering': ['-primary_key'],
            },
        ),
    ]
