# Generated by Django 4.2.8 on 2024-01-16 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_panel', '0010_alter_smstemplates_template_descriptions_churchzones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchzones',
            name='zone_members',
        ),
    ]
