# Generated by Django 4.2.8 on 2024-01-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitos_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='churchvisitors',
            old_name='visitor_resident',
            new_name='visitor_resident_city',
        ),
        migrations.AddField(
            model_name='churchvisitors',
            name='visitor_resident_street',
            field=models.CharField(blank=True, default='', max_length=9000, null=True),
        ),
    ]
