# Generated by Django 4.2.8 on 2024-01-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitos_management', '0002_rename_visitor_resident_churchvisitors_visitor_resident_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='churchvisitors',
            options={'ordering': ['-primary_key'], 'verbose_name_plural': 'VISITORS'},
        ),
        migrations.AddField(
            model_name='churchvisitors',
            name='visitor_photo',
            field=models.CharField(blank=True, max_length=9000, null=True),
        ),
    ]
