# Generated by Django 4.2.8 on 2024-01-20 20:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members_management', '0008_churchchildren'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenths',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('tenth_unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tenth_amount', models.IntegerField(default=0, null=True)),
                ('tenth_date', models.DateField(blank=True, max_length=9000, null=True)),
                ('tenth_registered_date', models.DateTimeField(auto_now_add=True)),
                ('tenth_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenth_members', to='members_management.churchmembers')),
            ],
            options={
                'verbose_name_plural': 'TENTHS',
                'db_table': 'church_tenths_tbl',
                'db_table_comment': 'Church Tenths',
                'ordering': ['-primary_key'],
            },
        ),
    ]
