# Generated by Django 4.2.8 on 2024-01-14 10:09

from django.db import migrations, models
import utils.Enums
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchMembers',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('member_unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('member_name', models.CharField(max_length=9000)),
                ('member_gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=9000)),
                ('member_phone', models.CharField(max_length=9000)),
                ('member_email', models.CharField(blank=True, default='', max_length=9000, null=True)),
                ('member_resident_city', models.CharField(blank=True, default='', max_length=9000, null=True)),
                ('member_resident_street', models.CharField(blank=True, default='', max_length=9000, null=True)),
                ('member_maritual_stattus', models.CharField(blank=True, choices=[('VISITING', 'VISITING'), ('JOINING', 'JOINING')], default=utils.Enums.VisitReasonsInum['VISITING'], max_length=9000, null=True)),
                ('member_education_level', models.CharField(blank=True, choices=[('PRAYER', 'PRAYER'), ('SALVATION', 'SALVATION'), ('COUNCELING', 'COUNCELING')], default=utils.Enums.SpiritualAsistanceInum['PRAYER'], max_length=9000, null=True)),
                ('member_registered_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Members',
                'db_table': 'church_members_tbl',
                'db_table_comment': 'Church members',
                'ordering': ['-primary_key'],
            },
        ),
    ]
