# Generated by Django 4.2.8 on 2024-01-14 10:17

from django.db import migrations, models
import utils.Enums


class Migration(migrations.Migration):

    dependencies = [
        ('members_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchmembers',
            name='member_maritual_stattus',
        ),
        migrations.AddField(
            model_name='churchmembers',
            name='member_maritual_status',
            field=models.CharField(blank=True, choices=[('MARRIED', 'MARRIED'), ('WIDOW', 'WIDOW'), ('WIDOWER', 'WIDOWER'), ('SINGLE', 'SINGLE')], default=utils.Enums.MaritualStatusInum['SINGLE'], max_length=9000, null=True),
        ),
        migrations.AddField(
            model_name='churchmembers',
            name='member_occupation',
            field=models.CharField(blank=True, default='', max_length=9000, null=True),
        ),
        migrations.AlterField(
            model_name='churchmembers',
            name='member_education_level',
            field=models.CharField(blank=True, choices=[('NONE', 'NONE'), ('STANDARD_SEVEN', 'STANDARD_SEVEN'), ('FORM_IV', 'FORM_IV'), ('FORM_VI', 'FORM_VI'), ('DIPLOMA', 'DIPLOMA'), ('CERTIFICATE', 'CERTIFICATE'), ('DEGREE', 'DEGREE'), ('MASTERS', 'MASTERS'), ('PhD', 'PhD')], max_length=9000, null=True),
        ),
    ]
