# Generated by Django 4.2.8 on 2024-01-14 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members_management', '0002_remove_churchmembers_member_maritual_stattus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='churchmembers',
            options={'ordering': ['-primary_key'], 'verbose_name_plural': 'MEMBERS'},
        ),
    ]
