# Generated by Django 4.2.8 on 2024-01-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_management', '0003_alter_churchmembers_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchmembers',
            name='member_photo',
            field=models.CharField(blank=True, max_length=9000, null=True),
        ),
    ]
