# Generated by Django 4.2.8 on 2024-01-16 17:31

from django.db import migrations, models
import utils.Enums


class Migration(migrations.Migration):

    dependencies = [
        ('members_management', '0004_churchmembers_member_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchmembers',
            name='member_maritual_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'SINGLE'), ('MARRIED', 'MARRIED'), ('WIDOW', 'WIDOW'), ('WIDOWER', 'WIDOWER')], default=utils.Enums.MaritualStatusInum['SINGLE'], max_length=9000, null=True),
        ),
    ]
