# Generated by Django 4.2.8 on 2024-01-16 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_panel', '0011_remove_churchzones_zone_members'),
        ('members_management', '0006_churchmembers_member_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchmembers',
            name='member_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_zones', to='management_panel.churchzones'),
        ),
    ]
