# Generated by Django 4.2.8 on 2024-01-16 17:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('management_panel', '0011_remove_churchzones_zone_members'),
        ('members_management', '0007_alter_churchmembers_member_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchChildren',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('child_unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('child_name', models.CharField(max_length=9000)),
                ('child_age', models.IntegerField(max_length=9000)),
                ('child_gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=9000)),
                ('child_resident_city', models.CharField(blank=True, default='', max_length=9000, null=True)),
                ('child_resident_street', models.CharField(blank=True, default='', max_length=9000, null=True)),
                ('child_registered_date', models.DateTimeField(auto_now_add=True)),
                ('child_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_zones', to='management_panel.churchzones')),
            ],
            options={
                'verbose_name_plural': 'CHILDRENS',
                'db_table': 'church_childrens_tbl',
                'db_table_comment': 'Church Childrens',
                'ordering': ['-primary_key'],
            },
        ),
    ]
